<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SvDistrictsSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        $districts = [
            ['district_name' => 'Carolina', 'municipality_id' => 1],
            ['district_name' => 'Chapeltique', 'municipality_id' =>  1],
            ['district_name' => 'Chinameca', 'municipality_id' =>  3],
            ['district_name' => 'Chirilagua', 'municipality_id' =>  2],
            ['district_name' => 'Ciudad Barrios', 'municipality_id' =>  1],
            ['district_name' => 'El transito', 'municipality_id' => 3],
            ['district_name' => 'Comacaran', 'municipality_id' => 2],
            ['district_name' => 'Lolotique', 'municipality_id' => 3],
            ['district_name' => 'Moncagua', 'municipality_id' => 2],
            ['district_name' => 'Nueva Guadalupe', 'municipality_id' => 3],
            ['district_name' => 'Nuevo Edén de San Juan', 'municipality_id' => 1],
            ['district_name' => 'Quelepa', 'municipality_id' => 2],
            ['district_name' => 'San Jorge', 'municipality_id' => 3],
            ['district_name' => 'San Miguel', 'municipality_id' => 2],
            ['district_name' => 'San Rafael Oriente', 'municipality_id' => 3],
            ['district_name' => 'San Antonio del Mosco', 'municipality_id' => 1],
            ['district_name' => 'San Gerardo', 'municipality_id' => 1],
            ['district_name' => 'San Luis de la Reina', 'municipality_id' => 1],
            ['district_name' => 'Sesori', 'municipality_id' => 1],
            ['district_name' => 'Uluazapa', 'municipality_id' => 2],
            ['district_name' => 'Aguilares', 'municipality_id' => 4],
            ['district_name' => 'Apopa', 'municipality_id' => 5],
            ['district_name' => 'Ayutuxtepeque', 'municipality_id' => 7],
            ['district_name' => 'Cuscatancingo', 'municipality_id' => 7],
            ['district_name' => 'Ciudad Delgado', 'municipality_id' => 7],
            ['district_name' => 'El Paisnal', 'municipality_id' => 4],
            ['district_name' => 'Guazapa', 'municipality_id' => 6],
            ['district_name' => 'Ilopango', 'municipality_id' => 6],
            ['district_name' => 'Mejicanos', 'municipality_id' => 7],
            ['district_name' => 'Nejapa', 'municipality_id' => 5],
            ['district_name' => 'Panchimalco', 'municipality_id' => 8],
            ['district_name' => 'Rosario de Mora', 'municipality_id' => 8],
            ['district_name' => 'San Marcos', 'municipality_id' => 8],
            ['district_name' => 'San Martín', 'municipality_id' => 6],
            ['district_name' => 'San Salvador', 'municipality_id' => 7],
            ['district_name' => 'Santiago Texacuangos', 'municipality_id' => 8],
            ['district_name' => 'Santo Tomás', 'municipality_id' => 8],
            ['district_name' => 'Soyapango', 'municipality_id' => 6],
            ['district_name' => 'Tonacatepeque', 'municipality_id' => 6],
            ['district_name' => 'Agua Caliente', 'municipality_id' => 10],
            ['district_name' => 'Arcatao', 'municipality_id' => 11],
            ['district_name' => 'Azacualpa', 'municipality_id' => 11],
            ['district_name' => 'Chalatenango (ciudad)', 'municipality_id' => 11],
            ['district_name' => 'Comalapa', 'municipality_id' => 11],
            ['district_name' => 'Citalá', 'municipality_id' => 9],
            ['district_name' => 'Concepción Quezaltepeque', 'municipality_id' => 11],
            ['district_name' => 'Dulce Nombre de María', 'municipality_id' => 10],
            ['district_name' => 'El Carrizal', 'municipality_id' => 11],
            ['district_name' => 'El Paraíso', 'municipality_id' => 10],
            ['district_name' => 'La Laguna', 'municipality_id' => 11],
            ['district_name' => 'La Palma', 'municipality_id' => 9],
            ['district_name' => 'La Reina', 'municipality_id' => 10],
            ['district_name' => 'Las Vueltas', 'municipality_id' => 11],
            ['district_name' => 'Nueva Concepción', 'municipality_id' => 10],
            ['district_name' => 'Nueva Trinidad', 'municipality_id' => 11],
            ['district_name' => 'Nombre de Jesús', 'municipality_id' => 11],
            ['district_name' => 'Ojos de Agua', 'municipality_id' => 11],
            ['district_name' => 'Potonico', 'municipality_id' => 11],
            ['district_name' => 'San Antonio de la Cruz', 'municipality_id' => 11],
            ['district_name' => 'San Antonio Los Ranchos', 'municipality_id' => 11],
            ['district_name' => 'San Fernando', 'municipality_id' => 10],
            ['district_name' => 'San Francisco Lempa', 'municipality_id' => 11],
            ['district_name' => 'San Francisco Morazán', 'municipality_id' => 10],
            ['district_name' => 'San Ignacio', 'municipality_id' => 9],
            ['district_name' => 'San Isidro Labrador', 'municipality_id' => 11],
            ['district_name' => 'San José Cancasque', 'municipality_id' => 11],
            ['district_name' => 'San José Las Flores', 'municipality_id' => 11],
            ['district_name' => 'San Luis del Carmen', 'municipality_id' => 11],
            ['district_name' => 'San Miguel de Mercedes', 'municipality_id' => 11],
            ['district_name' => 'San Rafael', 'municipality_id' => 10],
            ['district_name' => 'Santa Rita', 'municipality_id' => 10],
            ['district_name' => 'Tejutla', 'municipality_id' => 10],
            ['district_name' => 'Alegría', 'municipality_id' => 12],
            ['district_name' => 'Berlín', 'municipality_id' => 12],
            ['district_name' => 'California', 'municipality_id' => 13],
            ['district_name' => 'Concepción Batres', 'municipality_id' => 13],
            ['district_name' => 'El Triunfo', 'municipality_id' => 12],
            ['district_name' => 'Ereguayquín', 'municipality_id' => 13],
            ['district_name' => 'Estanzuelas', 'municipality_id' => 12],
            ['district_name' => 'Jiquilisco', 'municipality_id' => 14],
            ['district_name' => 'Jucuapa', 'municipality_id' => 12],
            ['district_name' => 'Jucuarán', 'municipality_id' => 13],
            ['district_name' => 'Mercedes Umaña', 'municipality_id' => 12],
            ['district_name' => 'Nueva Granada', 'municipality_id' => 12],
            ['district_name' => 'Ozatlán', 'municipality_id' => 13],
            ['district_name' => 'Puerto El Triunfo', 'municipality_id' => 14],
            ['district_name' => 'San Agustín', 'municipality_id' => 14],
            ['district_name' => 'San Buenaventura', 'municipality_id' => 12],
            ['district_name' => 'San Dionisio', 'municipality_id' => 13],
            ['district_name' => 'San Francisco Javier', 'municipality_id' => 14],
            ['district_name' => 'Santa Elena', 'municipality_id' => 13],
            ['district_name' => 'Santa María', 'municipality_id' => 13],
            ['district_name' => 'Santiago de María', 'municipality_id' => 12],
            ['district_name' => 'Tecapán', 'municipality_id' => 13],
            ['district_name' => 'Usulután', 'municipality_id' => 13],
            ['district_name' => 'Candelaria', 'municipality_id' => 16],
            ['district_name' => 'Cojutepeque', 'municipality_id' => 16],
            ['district_name' => 'El Carmen', 'municipality_id' => 16],
            ['district_name' => 'El Rosario', 'municipality_id' => 16],
            ['district_name' => 'Monte San Juan', 'municipality_id' => 16],
            ['district_name' => 'Oratorio de Concepción', 'municipality_id' => 15],
            ['district_name' => 'San Bartolomé Perulapía', 'municipality_id' => 15],
            ['district_name' => 'San Cristóbal', 'municipality_id' => 16],
            ['district_name' => 'San José Guayabal', 'municipality_id' => 15],
            ['district_name' => 'San Pedro Perulapán', 'municipality_id' => 15],
            ['district_name' => 'San Rafael Cedros', 'municipality_id' => 16],
            ['district_name' => 'San Ramón', 'municipality_id' => 16],
            ['district_name' => 'Santa Cruz Analquito', 'municipality_id' => 16],
            ['district_name' => 'Santa Cruz Michapa', 'municipality_id' => 16],
            ['district_name' => 'Suchitoto', 'municipality_id' => 15],
            ['district_name' => 'Tenancingo', 'municipality_id' => 16],
            ['district_name' => 'Apastepeque', 'municipality_id' => 17],
            ['district_name' => 'Guadalupe', 'municipality_id' => 18],
            ['district_name' => 'San Cayetano Istepeque', 'municipality_id' => 18],
            ['district_name' => 'San Esteban Catarina', 'municipality_id' => 17],
            ['district_name' => 'San Ildefonso', 'municipality_id' => 17],
            ['district_name' => 'San Lorenzo', 'municipality_id' => 17],
            ['district_name' => 'San Sebastián', 'municipality_id' => 17],
            ['district_name' => 'San Vicente', 'municipality_id' => 18],
            ['district_name' => 'Santa Clara', 'municipality_id' => 17],
            ['district_name' => 'Santo Domingo', 'municipality_id' => 17],
            ['district_name' => 'Tecoluca', 'municipality_id' => 18],
            ['district_name' => 'Tepetitán', 'municipality_id' => 18],
            ['district_name' => 'Verapaz', 'municipality_id' => 18],
            ['district_name' => 'Candelaria de la Frontera', 'municipality_id' => 22],
            ['district_name' => 'Chalchuapa', 'municipality_id' => 22],
            ['district_name' => 'Coatepeque', 'municipality_id' => 21],
            ['district_name' => 'El Congo', 'municipality_id' => 21],
            ['district_name' => 'El Porvenir', 'municipality_id' => 22],
            ['district_name' => 'Masahuat', 'municipality_id' => 19],
            ['district_name' => 'Metapán', 'municipality_id' => 19],
            ['district_name' => 'San Antonio Pajonal', 'municipality_id' => 22],
            ['district_name' => 'San Sebastián Salitrillo', 'municipality_id' => 22],
            ['district_name' => 'Santa Ana', 'municipality_id' => 20],
            ['district_name' => 'Santa Rosa Guachipilín', 'municipality_id' => 19],
            ['district_name' => 'Santiago de la Frontera', 'municipality_id' => 22],
            ['district_name' => 'Texistepeque', 'municipality_id' => 19],
            ['district_name' => 'Ahuachapán', 'municipality_id' => 24],
            ['district_name' => 'Apaneca', 'municipality_id' => 24],
            ['district_name' => 'Atiquizaya', 'municipality_id' => 23],
            ['district_name' => 'Concepción de Ataco', 'municipality_id' => 24],
            ['district_name' => 'El Refugio', 'municipality_id' => 23],
            ['district_name' => 'Guaymango', 'municipality_id' => 25],
            ['district_name' => 'Jujutla', 'municipality_id' => 25],
            ['district_name' => 'San Francisco Menéndez', 'municipality_id' => 25],
            ['district_name' => 'San Lorenzo', 'municipality_id' => 23],
            ['district_name' => 'San Pedro Puxtla', 'municipality_id' => 25],
            ['district_name' => 'Tacuba', 'municipality_id' => 24],
            ['district_name' => 'Turín', 'municipality_id' => 23],
            ['district_name' => 'Arambala', 'municipality_id' => 26],
            ['district_name' => 'Cacaopera', 'municipality_id' => 26],
            ['district_name' => 'Chilanga', 'municipality_id' => 27],
            ['district_name' => 'Corinto', 'municipality_id' => 26],
            ['district_name' => 'Delicias de Concepción', 'municipality_id' => 27],
            ['district_name' => 'El Divisadero', 'municipality_id' => 27],
            ['district_name' => 'El Rosario', 'municipality_id' => 26],
            ['district_name' => 'Gualococti', 'municipality_id' => 27],
            ['district_name' => 'Guatajiagua', 'municipality_id' => 27],
            ['district_name' => 'Joateca', 'municipality_id' => 26],
            ['district_name' => 'Jocoaitique', 'municipality_id' => 26],
            ['district_name' => 'Jocoro', 'municipality_id' => 27],
            ['district_name' => 'Lolotiquillo', 'municipality_id' => 27],
            ['district_name' => 'Meanguera', 'municipality_id' => 26],
            ['district_name' => 'Osicala', 'municipality_id' => 27],
            ['district_name' => 'Perquín', 'municipality_id' => 26],
            ['district_name' => 'San Carlos', 'municipality_id' => 27],
            ['district_name' => 'San Fernando', 'municipality_id' => 26],
            ['district_name' => 'San Francisco Gotera', 'municipality_id' => 27],
            ['district_name' => 'San Isidro', 'municipality_id' => 26],
            ['district_name' => 'San Simón', 'municipality_id' => 27],
            ['district_name' => 'Sensembra', 'municipality_id' => 27],
            ['district_name' => 'Sociedad', 'municipality_id' => 27],
            ['district_name' => 'Torola', 'municipality_id' => 26],
            ['district_name' => 'Yamabal', 'municipality_id' => 27],
            ['district_name' => 'Yoloaiquín', 'municipality_id' => 27],
            ['district_name' => 'Anamorós', 'municipality_id' => 28],
            ['district_name' => 'Bolivar', 'municipality_id' => 28],
            ['district_name' => 'Concepción de Oriente', 'municipality_id' => 28],
            ['district_name' => 'Conchagua', 'municipality_id' => 29],
            ['district_name' => 'El Carmen', 'municipality_id' => 29],
            ['district_name' => 'El Sauce', 'municipality_id' => 28],
            ['district_name' => 'Intipucá', 'municipality_id' => 29],
            ['district_name' => 'La Unión', 'municipality_id' => 29],
            ['district_name' => 'Lislique', 'municipality_id' => 28],
            ['district_name' => 'Meanguera del Golfo', 'municipality_id' => 29],
            ['district_name' => 'Nueva Esparta', 'municipality_id' => 28],
            ['district_name' => 'Pasaquina', 'municipality_id' => 28],
            ['district_name' => 'Polorós', 'municipality_id' => 28],
            ['district_name' => 'San Alejo', 'municipality_id' => 29],
            ['district_name' => 'San José La Fuente', 'municipality_id' => 28],
            ['district_name' => 'Santa Rosa de Lima', 'municipality_id' => 28],
            ['district_name' => 'Yayantique', 'municipality_id' => 29],
            ['district_name' => 'Yucuaiquín', 'municipality_id' => 29],
            ['district_name' => 'Acajutla', 'municipality_id' => 33],
            ['district_name' => 'Armenia', 'municipality_id' => 32],
            ['district_name' => 'Caluco', 'municipality_id' => 32],
            ['district_name' => 'Cuisnahuat', 'municipality_id' => 32],
            ['district_name' => 'Izalco', 'municipality_id' => 32],
            ['district_name' => 'Juayúa', 'municipality_id' => 30],
            ['district_name' => 'Nahuizalco', 'municipality_id' => 30],
            ['district_name' => 'Nahulingo', 'municipality_id' => 31],
            ['district_name' => 'Salcoatitán', 'municipality_id' => 30],
            ['district_name' => 'San Antonio del Monte', 'municipality_id' => 31],
            ['district_name' => 'San Julián', 'municipality_id' => 32],
            ['district_name' => 'Santa Catarina Masahuat', 'municipality_id' => 30],
            ['district_name' => 'Santa Isabel Ishuatán', 'municipality_id' => 32],
            ['district_name' => 'Santo Domingo de Guzmán', 'municipality_id' => 31],
            ['district_name' => 'Sonsonate', 'municipality_id' => 31],
            ['district_name' => 'Sonzacate', 'municipality_id' => 31],
            ['district_name' => 'Antiguo Cuscatlán', 'municipality_id' => 37],
            ['district_name' => 'Chiltiupán', 'municipality_id' => 38],
            ['district_name' => 'Ciudad Arce', 'municipality_id' => 35],
            ['district_name' => 'Colón', 'municipality_id' => 36],
            ['district_name' => 'Comasagua', 'municipality_id' => 39],
            ['district_name' => 'Huizúcar', 'municipality_id' => 37],
            ['district_name' => 'Jayaque', 'municipality_id' => 36],
            ['district_name' => 'Jicalapa', 'municipality_id' => 38],
            ['district_name' => 'La Libertad', 'municipality_id' => 38],
            ['district_name' => 'Nueva San Salvador (Santa Tecla)', 'municipality_id' => 39],
            ['district_name' => 'Nuevo Cuscatlán', 'municipality_id' => 37],
            ['district_name' => 'San Juan Opico', 'municipality_id' => 35],
            ['district_name' => 'Quezaltepeque', 'municipality_id' => 34],
            ['district_name' => 'Sacacoyo', 'municipality_id' => 36],
            ['district_name' => 'San José Villanueva', 'municipality_id' => 37],
            ['district_name' => 'San Matías', 'municipality_id' => 34],
            ['district_name' => 'San Pablo Tacachico', 'municipality_id' => 34],
            ['district_name' => 'Talnique', 'municipality_id' => 36],
            ['district_name' => 'Tamanique', 'municipality_id' => 38],
            ['district_name' => 'Teotepeque', 'municipality_id' => 38],
            ['district_name' => 'Tepecoyo', 'municipality_id' => 36],
            ['district_name' => 'Zaragoza', 'municipality_id' => 37],
            ['district_name' => 'Cuyultitán', 'municipality_id' => 40],
            ['district_name' => 'El Rosario', 'municipality_id' => 41],
            ['district_name' => 'Jerusalén', 'municipality_id' => 41],
            ['district_name' => 'Mercedes La Ceiba', 'municipality_id' => 41],
            ['district_name' => 'Olocuilta', 'municipality_id' => 40],
            ['district_name' => 'Paraíso de Osorio', 'municipality_id' => 41],
            ['district_name' => 'San Antonio Masahuat', 'municipality_id' => 41],
            ['district_name' => 'San Emigdio', 'municipality_id' => 41],
            ['district_name' => 'San Francisco Chinameca', 'municipality_id' => 40],
            ['district_name' => 'San Juan Nonualco', 'municipality_id' => 42],
            ['district_name' => 'San Juan Talpa', 'municipality_id' => 40],
            ['district_name' => 'San Juan Tepezontes', 'municipality_id' => 41],
            ['district_name' => 'San Luis Talpa', 'municipality_id' => 40],
            ['district_name' => 'San Luis La Herradura', 'municipality_id' => 41],
            ['district_name' => 'San Miguel Tepezontes', 'municipality_id' => 41],
            ['district_name' => 'San Pedro Masahuat', 'municipality_id' => 40],
            ['district_name' => 'San Pedro Nonualco', 'municipality_id' => 41],
            ['district_name' => 'San Rafael Obrajuelo', 'municipality_id' => 42],
            ['district_name' => 'Santa María Ostuma', 'municipality_id' => 41],
            ['district_name' => 'Santiago Nonualco', 'municipality_id' => 41],
            ['district_name' => 'Tapalhuaca', 'municipality_id' => 40],
            ['district_name' => 'Zacatecoluca', 'municipality_id' => 42],
            ['district_name' => 'Cinquera', 'municipality_id' => 44],
            ['district_name' => 'Dolores', 'municipality_id' => 43],
            ['district_name' => 'Guacotecti', 'municipality_id' => 43],
            ['district_name' => 'Ilobasco', 'municipality_id' => 44],
            ['district_name' => 'Jutiapa', 'municipality_id' => 44],
            ['district_name' => 'San Isidro', 'municipality_id' => 43],
            ['district_name' => 'Sensuntepeque', 'municipality_id' => 43],
            ['district_name' => 'Tejutepeque', 'municipality_id' => 44],
            ['district_name' => 'Victoria', 'municipality_id' => 43],

        ];

        DB::table('sv_districts')->insert($districts);
    }
}
